name: "Destroy Infrastructure"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-southeast-2"
          role-to-assume: "arn:aws:iam::160071257600:role/tw-infra-taohui-github-actions-role"

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Destroy resources
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve
